AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create state services for Terraform'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Terraform Configuration'
        Parameters:
          - ResourcePrefix

Parameters:
  ResourcePrefix:
    Description: The Prefix for most resources created by CloudFormation
    Type: String
    Default: state
    MaxLength: 25

Resources:
  # S3 bucket for Terraform state
  TerraformStateBucket:
    Type: 'AWS::S3::Bucket'
    # checkov:skip=CKV_AWS_18:Ensure AWS access logging is enabled on S3 buckets
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketName: !Sub tf-${ResourcePrefix}-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  TerraformStateBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref TerraformStateBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt 'TerraformStateBucket.Arn'
              - !Sub '${TerraformStateBucket.Arn}/*'
            Condition:
              Bool:
                'aws:SecureTransport': false

  # DynamoDB for Terraform lock
  TerraformLockTable:
    Type: 'AWS::DynamoDB::Table'
    # checkov:skip=CKV_AWS_119:Ensure DynamoDB tables are encrypted
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub 'tf-${ResourcePrefix}-${AWS::AccountId}-${AWS::Region}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true


Outputs:
  TerraformStateBucketName:
    Description: S3 bucket name for Terraform state file
    Value: !Ref TerraformStateBucket

  TerraformLockTableName:
    Description: DynamoDB table name for Terraform lock handling
    Value: !Ref TerraformLockTable
